In [26]:
#Requried intership
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,r2_score

In [27]:
#getting dataset-->Source(Github)
df = pd.read_csv("https://raw.githubusercontent.com/wessamsw/California_Houses_Price_Prediction/main/housing.csv")

In [28]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [29]:
#EDD
df.isnull().sum()


longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [30]:
df['total_bedrooms'].unique()

array([ 129., 1106.,  190., ..., 3008., 1857., 1052.], shape=(1924,))

In [31]:
df['total_bedrooms'].value_counts()

total_bedrooms
280.0     55
331.0     51
345.0     50
343.0     49
393.0     49
          ..
2009.0     1
2249.0     1
3114.0     1
1625.0     1
1742.0     1
Name: count, Length: 1923, dtype: int64

In [32]:
df['total_bedrooms'].mode()

0    280.0
Name: total_bedrooms, dtype: float64

In [33]:
df['total_bedrooms']=df['total_bedrooms'].fillna(280)

In [34]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [35]:
##remove the unwanted coloum
df.drop(columns=['ocean_proximity'],axis=1,inplace=True)

In [36]:
df.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0

#Train and Test and split

In [65]:
X=df.iloc[:,:-1]#except last cl all 
y=df.iloc[:,-1]#only last cl

In [66]:
X.head(1)


longitude  latitude  total_bedrooms  population  households  median_income
0    -122.23     37.88           129.0       322.0       126.0         8.3252

In [67]:
y.head(1)

0    452600.0
Name: median_house_value, dtype: float64

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [69]:
df.shape

(20640, 7)

In [70]:
X_train.shape

(16512, 6)

In [71]:
X_train.shape

(16512, 6)

In [72]:
y_train.shape

(16512,)

#feature scaling

In [73]:
scaler=StandardScaler()

In [74]:
X_train_scaled=scaler.fit_transform(X_train)

In [75]:
X_train_scaled

array([[ 1.27258656, -1.3728112 ,  0.21122752,  0.76827628,  0.32290591,
        -0.326196  ],
       [ 0.70916212, -0.87669601,  0.59309419, -0.09890135,  0.6720272 ,
        -0.03584338],
       [-0.44760309, -0.46014647, -0.49522582, -0.44981806, -0.43046109,
         0.14470145],
       ...,
       [ 0.59946887, -0.75500738,  0.07280085,  0.28983345,  0.07090859,
        -0.49697313],
       [-1.18553953,  0.90651045,  0.13962752,  0.30830275,  0.15490769,
         0.96545045],
       [-1.41489815,  0.99543676,  1.85325421,  1.04883375,  1.94776365,
        -0.68544764]], shape=(16512, 6))

In [80]:
X_test_scaled=scaler.transform(X_test)

In [81]:
X_test_scaled

array([[ 2.85347282e-01,  1.95100000e-01, -6.16945826e-01,
        -3.03010896e-02, -3.70086730e-01, -1.15508475e+00],
       [ 6.09747178e-02, -2.35490539e-01, -6.16945826e-01,
         1.21850767e-01,  2.20531996e-01, -7.08659050e-01],
       [-1.42487026e+00,  1.00947776e+00, -6.16945826e-01,
        -1.02419310e-01,  1.21539643e+00, -2.10401549e-01],
       ...,
       [-1.23041404e+00,  7.80141492e-01, -1.18581720e-03,
         1.39440577e-01,  1.78532442e-01,  2.80902421e+00],
       [-8.86069914e-02,  5.27403567e-01, -1.73025820e-01,
        -1.75417022e-01, -6.82149367e-02, -5.75429783e-01],
       [ 6.04454928e-01, -6.66081077e-01, -1.80185820e-01,
         2.15076760e-01, -1.36464212e-01, -1.72591114e-01]],
      shape=(4128, 6))

#Model Building

In [84]:
model=LinearRegression()

In [ ]:
model.fit(X_train_sca)